### ISSUE TITLE
Coin Dash - Missing audio file in assets/audio

### ISSUE THREAD

**Issue by davelearning** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#1]
> For this game, you’re going to add three sound effects. In the Main scene, add three AudioStreamPlayer nodes and name them CoinSound, LevelSound, and EndSound. Drag each sound from the res://assets/audio/ folder into the corresponding node’s Stream property.

However EndSound is missing from the assets:
https://github.com/PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition/tree/main/Chapter02%20-%20Coin%20Dash/coin_dash/assets/audio
![image](https://github.com/PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition/assets/9152535/92ddf605-be7f-4e00-bea8-79488161f733)

I may have missed something too ¯\_(ツ)_/¯

**Comment by cbscribe** [comment]
Hi, no you didn't miss anything, the file just wasn't there. :)

I've updated the example project and the zip download to include the "EndSound.wav" file.

Thanks!
