### ISSUE TITLE
Space Rocks - TextureProgressBar mentioned when not used

### ISSUE THREAD

**Issue by pres2300** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#10]
On Page 77 just below figure 3.22, the following statement is made:

> In this section, you made a much more complex UI than in previous projects, including some new 
Control nodes such as TextureProgressBar . . .

`TextureProgressBar` has not been used yet.

**Comment by cbscribe** [comment]
Indeed, that node is used later in making the shield functionality, which we moved to its own section at one point during the development.

Thanks for the correction!
