### ISSUE TITLE
Space Rocks - Instruction to add enemy to main node's `enemy_scene` inspector missing

### ISSUE THREAD

**Issue by pres2300** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#11]
An instruction to add the enemy to the main node's `enemy_scene` in the main node's inspector is missing.  If this is not done, you will get the following error when running the game: 

```
Cannot call method 'instantiate' on a null value.
```

This may be easily overlooked for someone like me that isn't used to working in Godot's UI yet.  The `@export var enemy_scene` implies this step needs to be done, but I haven't built the muscle memory to add it to the inspector at this point.

**Comment by cbscribe** [comment]
Thanks for the note. I'll update the next version of the PDF to include that reminder.
