### ISSUE TITLE
Coin Dash - Cactus - Missing Code?

### ISSUE THREAD

**Issue by davelearning** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#2]
At the end of chapter 2, the book instructs to create the cactus scene, then play the game and test interacting with the cactus. But there aren't any changes to the logic to instantiate the scene into the game. It doesn't look like anything exists in the code in the repo either.

I'd expect to see the cactus imported and spawned in a similar fashion to coins and powerup?

> Create a new Area2D scene and name it Cactus. Give it Sprite2D and CollisionShape2D children. Drag the cactus texture from FileSystem into the Texture property of Sprite2D. Add RectangleShape2D to the collision shape and size it so that it covers the image. Remember when you added if area.is_in_group("obstacles"?) to the player code? Add Cactus to the obstacles group using the Node tab. Play the game and see what happens when you run into the cactus.

**Comment by cbscribe** [comment]
Thanks for your message.

You're correct, there's a missing sentence there, before the last one:

> In the Main scene, add an instance of the Cactus object by pressing the "Instantiate Child Scene" button and then position it somewhere in the play area.

The idea was to add the cactus in the most simple way possible to demonstrate it working. If you want to extend the project to spawn multiple cactuses, that would be an excellent exercise to test your understanding.
