### ISSUE TITLE
Coin Dash - Missing Code for setting up PowerupTimer

### ISSUE THREAD

**Issue by pres2300** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#4]
On pg. 44 the book states "Add this to the _process() function after the new coins are 
spawned with spawn_coins():" without any code following it.

The code should be: 
```
$PowerupTimer.wait_time = randf_range(5, 10)
$PowerupTimer.start()
```

**Comment by JamesSkemp** [comment]
On that same page, near the top, it has a `<IMG>` placeholder instead of the image.

**Comment by cbscribe** [comment]
This has been corrected in the Errata file. Thanks for the post.
