### ISSUE TITLE
Coin Dash - Cacti do not appear

### ISSUE THREAD

**Issue by Roucou** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#6]
On p46-47 a Cactus scene is created, but this isn't actually incorporated in the game anywhere.

A potential fix would be to add an extra export in the `main.gd` script, after the `powerup_scene` export line:

```
@export var obstacle_scene : PackedScene
```

Don't forget to drag the `cactus.tscn` to the Obstacle Scene property of the Main node in the main scene!

Next, add these lines to the `spawn_coins()` function, just before the `for` loop:

```
get_tree().call_group("obstacles", "queue_free")
for i in 3:
   var o = obstacle_scene.instantiate()
   add_child(o)
   o.position = Vector2(randi_range(0, screensize.x), randi_range(0, screensize.y))
```

Overall, it would be clearer to rename the `spawn_coins()` function to `new_level()`.

Further improvements, left as an exercise to the reader:

- Don't spawn obstacles on top of the player.
- Make the player immune to the obstacles for the first two seconds at the start of a new level.
- Ensure the obstacles don't overlap.
- Ensure the obstacles don't touch the sides of the screens, as this could potentially make coins inaccessible.
- Random flip the obstacle's horizontal orientation, to bring some variety to the visuals.
- Increase the number of obstacles every couple of levels.

**Comment by Earph0nes** [comment]
I don't understand how this was missed. Doesn't give me very much confidence for the rest of the book.

**Comment by cbscribe** [comment]
As you've noted , spawning the obstacles automatically means  you have to make sure they don't overlap coins/player/etc.

The intention of the cactus was just that the user add it manually to the scene, but I agree the text is not clear that you should do that. I've added some clarifying text to the errata page.

Thanks for the post!
