### ISSUE TITLE
Space Rocks - Missing logic to score points for rocks in book (and enemy)

### ISSUE THREAD

**Issue by JamesSkemp** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#8]
While in main.gd in this repo, the logic to update the score when rocks are destroyed appears to be missing from the book.

I'm also not seeing logic to score points for destroying enemy ships.

**Comment by cbscribe** [comment]
Thanks for the note. I'm adding both of those lines to the errata and they'll get updated in the book's pdf by the publisher soon.
