### ISSUE TITLE
Space Rocks - Can't rotate while invulnerable?

### ISSUE THREAD

**Issue by grtwje** [PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition#9]
I noticed after the player hits a rock, explodes, and is invulnerable, the ship will not rotate until invulnerability is over. Thrust works fine.  If I comment out the "$CollisionShape2D.set_deferred("disabled", true)" in the transition to INVULNERABLE, rotation works.  Do I have a bug in my code, or is this the way it is supposed to work?

Windows 11, Godot 4.1.2.stable

**Comment by pres2300** [comment]
I noticed the same thing.  However, if you comment out `$CollisionShape2D.set_deferred("disabled", true` the ship remains vulnerable (you can still get damaged by rocks).

EDIT: My workaround was to remove `$CollisionShape2D.set_deferred("disabled", true)` in the `INVULNERABLE` state add a check for the `ALIVE` in `_on_body_entered` for the player:
`if body.is_in_group("rocks") and state == ALIVE:`

**Comment by grtwje** [comment]
Thank you!

**Comment by grtwje** [comment]
Found out it is a known issue:
https://github.com/godotengine/godot/issues/41024
